### PR TITLE
Create release.yml, addresses #10

### PR DESCRIPTION
**Pull request by slightknack**
This is a base GitHub Action that builds a number of binaries and adds them to a draft release. I'm not sure if it's correct, which is why I'm putting it in as a PR for review.

### CODE REVIEW

**Review by rishiosaur — APPROVED** [review]
LGTM!

**Comment by rishiosaur** [comment]
Wait nope nvm i'll need to fix some stuff

**Comment by rishiosaur** [comment]
@slightknack I'd also add an actual release creation section - maybe use [this?](https://github.com/marketplace/actions/publish-crates)

**Comment by slightknack** [comment]
like?

```yaml
- name: Upload Release Assets
- uses: katyo/publish-crates@v1
  with:
      registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      path: ./passerine

- uses: katyo/publish-crates@v1
  with:
      registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      path: ./aspen
```

Should this be a separate job?

**Comment by slightknack** [comment]
It's a bit annoying that you have to push to see whether actions work. I know there's (act)[https://github.com/nektos/act], but then again...

**Pull request merged**
